const app = document.querySelector("#app");
const toast = document.querySelector("#toast");
const STORAGE_KEY = "good-company-prototype-v1";

const questions = [
  { dimension:"Daily pace", icon:"☀️", prompt:"The first morning is wide open. What sounds like a lovely start?", choices:["Coffee slowly, then see how we feel","A gentle plan, with room to wander","Out the door early while the day is fresh"] },
  { dimension:"Daily pace", icon:"🌿", prompt:"By late afternoon, your ideal trip day has…", choices:["One or two memorable things, with a real pause","A full day, as long as there’s a little breathing room","As much exploring as we can fit in"] },
  { dimension:"Planning", icon:"🗓️", prompt:"A dinner spot everyone will love is popular. When do you want to decide?", choices:["Let’s pick a night and book it now","Save a few options and decide closer to the day","Keep the evening open and follow the mood"] },
  { dimension:"Planning", icon:"🧭", prompt:"For a day out, how much of the plan feels good?", choices:["A loose shape and one thing we’re excited about","A couple of anchors, with free time between","Let’s make the most of the day with a clear plan"] },
  { dimension:"Budget", icon:"🪙", prompt:"When it comes to the shared stay, you feel best when…", choices:["We agree on a comfortable range up front","We compare a few options and balance price with comfort","I’m happy to spend more for a place that feels special"] },
  { dimension:"Budget", icon:"🍰", prompt:"A wonderful meal is a little pricier than expected. Your first thought?", choices:["I’d rather keep most meals easy on the budget","One special meal sounds great if we plan for it","Let’s go for it if it feels worth the memory"] },
  { dimension:"Food", icon:"🥐", prompt:"How should meals fit into the trip?", choices:["A good meal is one of the best parts of going","Let’s choose a few spots, then stay flexible","Food is fuel between the things we came to do"] },
  { dimension:"Food", icon:"🍜", prompt:"It’s lunchtime and everyone’s hungry. The ideal move is…", choices:["A place we’ve been looking forward to","Somewhere nearby that looks good","A quick bite so we can keep exploring"] },
  { dimension:"Social energy", icon:"🫶", prompt:"On a group trip, a little time to yourself feels…", choices:["Lovely. I recharge with quiet moments","Good sometimes, especially after a full day","I usually want to keep the group together"] },
  { dimension:"Social energy", icon:"📚", prompt:"Someone wants a quiet hour back at the stay. You think…", choices:["That sounds nice; I might join them","Great, we can split up and meet later","I’d rather find something we can all do"] },
  { dimension:"Nightlife", icon:"🌙", prompt:"After a long dinner, what sounds like the right kind of evening?", choices:["A slow walk, then a cozy wind-down","One more stop if the group’s feeling it","Let’s see where the night takes us"] },
  { dimension:"Nightlife", icon:"✨", prompt:"On vacation, your favorite late-night memory is usually…", choices:["A peaceful end to a day well spent","Laughing over one last drink or dessert","A spontaneous night that became a story"] },
];
const dimensions = ["Budget","Daily pace","Planning","Food","Social energy","Nightlife"];
const types = [
  { name:"The Slow Starter", line:"Good coffee. A little room. Then let’s go.", className:"day", art:"palm", share:"A soft start makes the whole day feel like yours." },
  { name:"The Daylight Drifter", line:"A little plan, a lot of room to wander.", className:"day", art:"sun", share:"One lovely anchor. Plenty of room around it." },
  { name:"The Easygoing Explorer", line:"A good plan is one that leaves room for more.", className:"day", art:"hill", share:"Curiosity first. The rest can find its way." },
  { name:"The After-Dinner Walker", line:"One more block. Maybe two.", className:"night", art:"moon", share:"The day can be full and the evening still unhurried." },
  { name:"The Sunset Seeker", line:"Let’s make a day of it, then see where we land.", className:"night", art:"sunset", share:"A full day, with a little magic left after dinner." },
  { name:"The Last-Light Wanderer", line:"The best plans leave space for a story.", className:"night", art:"stars", share:"Stay curious. The night has a little room left." },
];
const questionFlow = [
  { title:"Let’s make mornings feel good", prompt:"The group has a mix of early risers and slow starters. What kind of rhythm would you like to try?", options:["Keep a couple of mornings open","Pick one early outing, then leave the rest flexible","Agree on a relaxed meet-up time each day"] },
  { title:"A little clarity around spending", prompt:"People have different comfort zones. What would help everyone feel at ease before booking?", options:["Set a comfortable range for the shared stay","Share a couple of price options before deciding","Keep shared costs simple and plan splurges together"] },
  { title:"Together, with room to wander", prompt:"Some people recharge together; some like a little solo time. What sounds welcoming?", options:["Make it easy to split up and meet back later","Choose one shared anchor each day","Check in with each other as we go"] },
];

function defaultState(){ return { screen:"home", tripName:"", groupSize:5, answers:Array(12).fill(null), questionIndex:0, isSample:false, promptIndex:0, selectedPrompt:null, flowAnswers:[], completed:false }; }
function loadState(){ try { return {...defaultState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")}; } catch { return defaultState(); } }
let state = loadState();
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function esc(value){ return String(value).replace(/[&<>"']/g, ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch])); }
function showToast(message){ toast.textContent=message; toast.classList.add("show"); setTimeout(()=>toast.classList.remove("show"),2300); }
function setScreen(screen){ state.screen=screen; save(); render(); window.scrollTo({top:0,behavior:"smooth"}); }
function svgLogo(){ return `<img class="hero-logo" src="assets/good-company-mark.png" alt="The Good Company coral day card and teal night card, joined by a hand-drawn line" />`; }
function cardArt(kind){
  if(kind==="palm") return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><circle cx="27" cy="44" r="14" fill="none" stroke="currentColor" stroke-width="3"/><path d="M43 59c-4-24-2-38 6-52m-6 16C33 14 27 13 18 14m25 10c3-11 11-17 21-18M43 34c13-7 22-5 29 1m-31 9c-12-9-22-8-30-3m1 25c25-9 44-10 65-7" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`;
  if(kind==="moon"||kind==="stars") return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><path d="M47 9a19 19 0 1 0 20 25A21 21 0 0 1 47 9Z" fill="currentColor"/><path d="m9 61 20-25 15 17 12-21 17 29H9Z" fill="currentColor"/><path d="M15 69h52M21 73h38" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="m15 20 2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5Zm47 12 1.5 4 4 1.5-4 1.5-1.5 4-1.5-4-4-1.5 4-1.5 1.5-4Z" fill="currentColor"/></svg>`;
  return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><circle cx="40" cy="37" r="19" fill="none" stroke="currentColor" stroke-width="3"/><path d="M40 3v9m0 50v10M6 37h9m50 0h9M16 13l7 7m34 34 7 7m0-48-7 7M23 54l-7 7" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M40 18v19l13 8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`;
}

function homeScreen(){ return `<section class="home-hero"><div class="hero-copy"><div class="eyebrow">A little check-in, before the group books</div><h1>It's your<br>trip, too.</h1><p>Different people. Different perfect days. Take a playful minute to see what kind of trip everyone has in mind—then find an easy way to talk about it.</p><div class="button-row"><button class="btn btn-coral" data-action="create">Start a trip <span>↗</span></button><button class="btn btn-secondary" data-action="sample">Take a look around</button></div></div><div class="hero-art">${svgLogo()}<div class="hero-art-caption"><span>Different ways to travel.</span><span>One good way to begin.</span></div></div></section><section class="value-strip"><div class="value-item"><strong>01 · Take the Trip Check</strong>12 small questions. No right answers.</div><div class="value-item"><strong>02 · Meet your travel type</strong>A playful snapshot, just for this trip.</div><div class="value-item"><strong>03 · Find your group rhythm</strong>A few easy conversations, together.</div></section>`; }
function createScreen(){ return `<div class="create-header"><div class="eyebrow">Start with the trip, not the spreadsheet</div><h2>Who are we going with?</h2><p class="muted">Give your trip a name. You’ll get an invite to share with your people.</p></div><form class="panel form-panel" id="create-form"><label class="field-label" for="trip-name">What should we call it?</label><input class="text-input" id="trip-name" name="tripName" maxlength="48" placeholder="e.g. Palm Springs, finally" required value="${esc(state.tripName)}"><span class="field-label">How many of you are going?</span><div class="size-control"><button type="button" aria-label="Remove one traveler" data-action="size-down">−</button><span class="size-count"><span id="size-value">${state.groupSize}</span> people</span><button type="button" aria-label="Add one traveler" data-action="size-up">+</button></div><div class="privacy-note"><strong>Your answers stay yours.</strong> Friends see group patterns and conversation prompts, not your individual picks.</div><div class="button-row"><button class="btn btn-coral" type="submit">Create the trip <span>↗</span></button><button class="text-button" type="button" data-action="home">Back</button></div></form>`; }
function inviteScreen(){ const inviteUrl=`${location.href.split("#")[0]}#trip-${encodeURIComponent(state.tripName||"good-company")}`; return `<section class="center-page"><div class="eyebrow">Your trip is ready</div><h2>${esc(state.tripName || "A little getaway")}</h2><p class="muted">Send this little check-in to your people. Everyone gets a travel type; the group conversation opens after three people respond.</p><div class="invite-card"><div class="eyebrow" style="color:#fda28f">Your invitation</div><h3 class="serif" style="font-size:26px;margin:10px 0">“Before we book anything, let’s see what kind of trip we each want.”</h3><p>A small check-in for our trip. Find your travel type and help us find our group rhythm.</p><div class="link-row"><div class="link-box" id="invite-link">${esc(inviteUrl)}</div><button class="btn btn-coral" data-action="copy-invite">Copy link</button></div></div><div class="steps-list"><div class="step-row"><span class="step-num">1</span><span>Share the link in your group chat.</span></div><div class="step-row"><span class="step-num">2</span><span>Everyone answers 12 quick questions—no account needed.</span></div><div class="step-row"><span class="step-num">3</span><span>Come back together for patterns and a few easy conversations.</span></div></div><div class="privacy-note"><strong>Prototype note:</strong> this demo stores progress on this device only. Invite links won’t sync answers between different people yet.</div><div class="button-row"><button class="btn" data-action="begin">Take the Trip Check <span>→</span></button><button class="btn btn-secondary" data-action="home">Home</button></div></section>`; }
function quizScreen(){ const i=state.questionIndex,q=questions[i],chosen=state.answers[i]; return `<section class="quiz-wrap"><div class="quiz-top"><span>YOUR TRIP CHECK</span><span>${i+1} of ${questions.length}</span></div><div class="progress" aria-label="${i+1} of 12 questions complete"><span style="width:${((i+1)/questions.length)*100}%"></span></div><div class="panel question-panel"><div class="question-subtitle">A little about ${q.dimension.toLowerCase()}</div><h2 class="question-title">${q.prompt}</h2><p class="question-helper">Go with what feels right for this trip. There’s no wrong answer.</p><div class="answer-list">${q.choices.map((c,n)=>`<button class="answer-option ${chosen===n?"selected":""}" data-action="answer" data-value="${n}" aria-pressed="${chosen===n}"><span class="answer-icon">${q.icon}</span><span class="answer-copy">${c}</span><span class="answer-check">✓</span></button>`).join("")}</div><div class="quiz-actions"><button class="text-button" data-action="quiz-back">${i===0?"Save for later":"← Back"}</button><button class="btn btn-coral" data-action="quiz-next" ${chosen===null?"disabled":""}>${i===questions.length-1?"Meet your type":"Next"} <span>→</span></button></div></div><p class="tiny-note" style="text-align:center;margin-top:13px">Your picks are private. We only use them to make your personal result.</p></section>`; }
function score(){ const out=Object.fromEntries(dimensions.map(d=>[d,[]])); questions.forEach((q,i)=>{if(state.answers[i]!==null) out[q.dimension].push(state.answers[i]??1);}); return Object.fromEntries(dimensions.map(d=>{const a=out[d]; const mean=a.length?a.reduce((x,y)=>x+y,0)/a.length:2; return [d,Math.round((mean-1)*50)];})); }
function travelType(scores){ const energy=(scores["Daily pace"]+scores[PlanningKey()]+scores.Food+scores["Nightlife"])/4; const social=(scores["Social energy"]+scores["Nightlife"])/2; const dayLean=scores["Daily pace"]<50 && scores.Nightlife<55; let index=dayLean?(energy<30?0:energy<58?1:2):(social<34?3:social<67?4:5); return types[index]; }
function PlanningKey(){return "Planning";}
function profileMarkup(scores){return `<div class="profile-list">${dimensions.map((d,i)=>`<div class="dimension-row"><span class="dimension-label">${d}</span><span class="dimension-track"><span class="dimension-fill" style="width:${Math.max(7,scores[d])}%;background:${i%2?"var(--teal)":"var(--blue)"}"></span></span><span class="dimension-value">${scores[d]<34?"More room":"Somewhere between"}</span></div>`).join("")}</div>`;}
function resultScreen(){ const scores=score(),type=travelType(scores); return `<section class="center-page"><div class="eyebrow">Your travel type · just for this trip</div><h2>A little more you, in the mix.</h2><p class="muted">This is a playful snapshot of what you picked—not a personality test, and not a label that has to stick.</p><div class="card-layout"><article class="type-card ${type.className}" id="share-card"><div class="card-topline"><span>Your travel type</span><span>${type.className==="day"?"Day card":"Night card"}</span></div><div class="card-middle">${cardArt(type.art)}<div class="card-overline">An affectionate little snapshot</div><h3 class="card-title">${type.name}</h3><div class="card-tagline">${type.line}</div></div><div class="card-bottomline"><span>good company.</span><span>What's your type? ↗</span></div></article><div class="result-copy"><span class="eyebrow">A private look at your answers</span>${profileMarkup(scores)}<p class="tiny-note">Your group won’t see these individual picks or dimension details. They’ll see patterns once enough people answer.</p><div class="share-actions"><button class="btn btn-coral" data-action="share-card" data-format="story">Save Story card ↗</button><button class="btn btn-secondary" data-action="share-card" data-format="square">Save square card ↗</button><button class="text-button" data-action="copy-type">Copy my result</button></div><p class="tiny-note" style="margin-top:13px">${esc(type.share)}</p></div></div><div style="display:flex;justify-content:space-between;gap:15px;align-items:center;margin-top:28px"><button class="text-button" data-action="delete-answer">Delete my answers</button><button class="btn" data-action="group">See our group rhythm <span>→</span></button></div></section>`; }
function insightPanel(){ return `<div class="panel"><div class="eyebrow">Based on 4 of 5 responses</div><h3 class="serif" style="font-size:25px;margin-top:7px">A few things to keep in mind</h3><div class="insight-list"><div class="insight-item"><div class="insight-symbol">☀️</div><div><strong>Everyone has room for an unhurried start</strong><span>A slow first morning might help the trip feel good from day one.</span></div></div><div class="insight-item"><div class="insight-symbol">🍽️</div><div><strong>A shared meal could be a lovely anchor</strong><span>Food matters to a few of you. Picking one dinner together could be a fun place to start.</span></div></div><div class="insight-item"><div class="insight-symbol">🌿</div><div><strong>Some of you like a little breathing room</strong><span>It could feel easy to leave space for people to wander, then meet back up.</span></div></div></div><p class="tiny-note" style="margin:13px 0 0">Patterns, not people. No individual answers or scores appear here.</p></div>`; }
function conversationCard(){ const i=state.promptIndex, q=questionFlow[i]; if(state.promptIndex>=questionFlow.length) return `<div class="conversation-card"><div class="conversation-step">A good start, together</div><div style="font-size:31px;margin-bottom:9px">✳</div><h3>You’ve made a little room for everyone.</h3><p>Your group has a few starting points to bring into the planning chat. Nothing is set in stone—you can come back to these whenever it helps.</p><div class="result-banner">“${esc(state.flowAnswers[0] || "Let’s keep a couple of mornings open and decide together.") }”</div><div class="conversation-footer"><button class="text-button" data-action="flow-restart">Start another</button><button class="btn" data-action="home">All done ✓</button></div></div>`; return `<div class="conversation-card"><div class="conversation-step">A quick group flow · ${i+1} of ${questionFlow.length}</div><h3>${q.title}</h3><p>${q.prompt}</p><div class="prompt-options">${q.options.map((o,n)=>`<button class="prompt-option ${state.selectedPrompt===o?"selected":""}" data-action="prompt-choice" data-value="${n}">${o}</button>`).join("")}</div><div class="conversation-footer"><button class="text-button" data-action="prompt-skip">Maybe later</button><button class="btn" data-action="prompt-next" ${state.selectedPrompt?"":"disabled"}>${i===questionFlow.length-1?"Keep this thought":"Next"} →</button></div></div>`; }
function dashboardScreen(){ return `<section><div class="section-head"><div><div class="eyebrow">The ${esc(state.tripName||"weekend")}, together</div><h2>Different days. One good group.</h2></div><button class="btn btn-secondary" data-action="copy-invite">Invite your people ↗</button></div><div class="dashboard-grid"><div>${insightPanel()}<div class="panel response-card" style="margin-top:15px"><div><div class="eyebrow">Your group, so far</div><div class="response-count">4<small> / 5 answered</small></div><p class="tiny-note" style="margin:7px 0 0">The shared view opens after three people check in.</p></div><div class="avatar-stack" aria-label="Four friends have answered"><span class="avatar">A</span><span class="avatar">M</span><span class="avatar">J</span><span class="avatar">Y</span><span class="avatar">+</span></div></div></div><div>${conversationCard()}<div class="privacy-note"><strong>A note on this prototype:</strong> sample group patterns are illustrative. In a live product, people’s individual answers would remain private.</div></div></div></section>`; }
function completionScreen(){return `<section class="completion-screen"><div class="completion-icon">✓</div><div class="eyebrow">That’s everyone in the room</div><h2>You're part of the group rhythm.</h2><p class="muted">Your choice is just one voice in the mix. The best next step is whatever feels easy for your group.</p><div class="result-banner" style="text-align:left;margin:25px 0">Your private response has been saved on this device. You can revisit your travel type or delete your answers anytime.</div><div class="button-row" style="justify-content:center"><button class="btn" data-action="result">See my travel type</button><button class="btn btn-secondary" data-action="group">Back to the group</button></div></section>`;}
function render(){ let view={home:homeScreen,create:createScreen,invite:inviteScreen,quiz:quizScreen,result:resultScreen,group:dashboardScreen,complete:completionScreen}[state.screen]||homeScreen; app.innerHTML=view(); document.querySelectorAll(".btn:disabled").forEach(b=>{b.style.opacity=".45";b.style.cursor="not-allowed";}); }
async function copyText(text){ try{await navigator.clipboard.writeText(text);showToast("Copied. Ready to share!");}catch{showToast("Copy isn’t available here—select the link to copy it.");} }
function exportCard(format="story"){ const square=format==="square",scores=score(),type=travelType(scores),night=type.className==="night",bg=night?"#67ADAC":"#FE664D";const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=square?1080:1920;const c=canvas.getContext("2d");c.fillStyle=bg;c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle="#021A25";c.font="700 27px 'DM Sans',sans-serif";c.letterSpacing="5px";c.fillText("YOUR TRAVEL TYPE",72,88);c.textAlign="right";c.fillText(night?"NIGHT CARD":"DAY CARD",1008,88);c.textAlign="left";c.strokeStyle="rgba(2,26,37,.5)";c.lineWidth=7;c.lineCap="round";c.beginPath();if(square){c.moveTo(40,700);c.bezierCurveTo(310,900,770,870,1035,610);}else{c.moveTo(95,1330);c.bezierCurveTo(280,1510,790,1485,990,1130);}c.stroke();const baseline=square?460:1090;c.font="500 38px 'Playfair Display',Georgia,serif";c.fillText("An affectionate little snapshot",72,baseline);c.font=`italic 500 ${square?80:98}px 'Playfair Display',Georgia,serif`;wrapCanvas(c,type.name,72,baseline+112,920,square?91:112);c.font="500 34px 'DM Sans',sans-serif";wrapCanvas(c,type.line,72,square?670:1510,890,51);c.beginPath();c.moveTo(72,square?930:1745);c.lineTo(1008,square?930:1745);c.lineWidth=3;c.stroke();c.font="700 25px 'DM Sans',sans-serif";c.fillText("good company.",72,square?986:1810);c.textAlign="right";c.fillText("What’s your type? ↗",1008,square?986:1810);c.textAlign="left";const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`good-company-travel-type-${format}.png`;a.click();showToast(`Your ${square?"square":"Story"} card is ready to save and share.`);}
function wrapCanvas(c,text,x,y,maxWidth,lineHeight){const words=text.split(" ");let line="";for(const word of words){const test=line+word+" ";if(c.measureText(test).width>maxWidth&&line){c.fillText(line,x,y);line=word+" ";y+=lineHeight;}else line=test;}c.fillText(line,x,y);}

app.addEventListener("submit",event=>{if(event.target.id==="create-form"){event.preventDefault();state.tripName=new FormData(event.target).get("tripName").trim();state.answers=Array(12).fill(null);state.questionIndex=0;state.isSample=false;setScreen("invite");}});
document.addEventListener("click",event=>{const el=event.target.closest("[data-action]");if(!el)return;const action=el.dataset.action;switch(action){case"home":state.screen="home";state.isSample=false;save();render();break;case"create":state.groupSize=5;setScreen("create");break;case"sample":state.tripName="A long weekend in Ojai";state.isSample=true;state.screen="group";state.promptIndex=0;state.selectedPrompt=null;state.flowAnswers=[];save();render();break;case"size-down":state.groupSize=Math.max(3,state.groupSize-1);save();render();break;case"size-up":state.groupSize=Math.min(10,state.groupSize+1);save();render();break;case"copy-invite":copyText(document.querySelector("#invite-link")?.textContent||`${location.href.split("#")[0]}#trip-${encodeURIComponent(state.tripName||"good-company")}`);break;case"begin":state.questionIndex=0;setScreen("quiz");break;case"answer":state.answers[state.questionIndex]=Number(el.dataset.value);save();render();break;case"quiz-next":if(state.answers[state.questionIndex]===null)return;if(state.questionIndex<11){state.questionIndex++;save();render();}else{state.completed=true;setScreen("result");}break;case"quiz-back":if(state.questionIndex>0){state.questionIndex--;save();render();}else setScreen("invite");break;case"result":setScreen("result");break;case"group":state.screen="group";save();render();break;case"share-card":exportCard(el.dataset.format);break;case"copy-type":copyText(`${travelType(score()).name} — ${travelType(score()).line} Take the Trip Check: ${location.href.split("#")[0]}`);break;case"delete-answer":if(confirm("Delete your answers from this device? This cannot be undone.")){state.answers=Array(12).fill(null);state.completed=false;state.screen="home";save();render();showToast("Your answers have been deleted.");}break;case"prompt-choice":state.selectedPrompt=questionFlow[state.promptIndex].options[Number(el.dataset.value)];save();render();break;case"prompt-next":if(!state.selectedPrompt)return;state.flowAnswers[state.promptIndex]=state.selectedPrompt;state.promptIndex++;state.selectedPrompt=null;if(state.promptIndex>=questionFlow.length){state.screen="complete";}save();render();break;case"prompt-skip":state.flowAnswers[state.promptIndex]=null;state.promptIndex++;state.selectedPrompt=null;if(state.promptIndex>=questionFlow.length)state.screen="complete";save();render();break;case"flow-restart":state.promptIndex=0;state.selectedPrompt=null;state.flowAnswers=[];save();render();break;}});
render();
