const app = document.querySelector("#app");
const toast = document.querySelector("#toast");
const STORAGE_KEY = "good-company-prototype-v1";
let shareFormat = "story";

const questions = [
  { dimension:"Daily pace", icon:"☀️", prompt:"The first morning is wide open. What sounds like a lovely start?", choices:["Coffee slowly, then see how we feel","A gentle plan, with room to wander","Out the door early while the day is fresh"] },
  { dimension:"Daily pace", icon:"🌿", prompt:"By late afternoon, your ideal trip day has…", choices:["One or two memorable things, with a real pause","A full day, as long as there’s a little breathing room","As much exploring as we can fit in"] },
  { dimension:"Planning", icon:"🗓️", prompt:"A dinner spot everyone will love is popular. When do you want to decide?", choices:["Let’s pick a night and book it now","Save a few options and decide closer to the day","Keep the evening open and follow the mood"] },
  { dimension:"Planning", icon:"🧭", prompt:"For a day out, how much of the plan feels good?", choices:["A loose shape and one thing we’re excited about","A couple of anchors, with free time between","Let’s make the most of the day with a clear plan"] },
  { dimension:"Budget", icon:"🪙", prompt:"When it comes to the shared stay, you feel best when…", choices:["We agree on a comfortable range up front","We compare a few options and balance price with comfort","I’m happy to spend more for a place that feels special"] },
  { dimension:"Budget", icon:"🍰", prompt:"A wonderful meal is a little pricier than expected. Your first thought?", choices:["I’d rather keep most meals easy on the budget","One special meal sounds great if we plan for it","Let’s go for it if it feels worth the memory"] },
  { dimension:"Food", icon:"🥐", prompt:"How should meals fit into the trip?", choices:["A good meal is one of the best parts of going","Let’s choose a few spots, then stay flexible","Food is fuel between the things we came to do"] },
  { dimension:"Food", icon:"🍜", prompt:"It’s lunchtime and everyone’s hungry. The ideal move is…", choices:["A place we’ve been looking forward to","Somewhere nearby that looks good","A quick bite so we can keep exploring"] },
  { dimension:"Social energy", icon:"🫶", prompt:"On a group trip, a little time to yourself feels…", choices:["Lovely. I recharge with quiet moments","Good sometimes, especially after a full day","I usually want to keep the group together"] },
  { dimension:"Social energy", icon:"📚", prompt:"Someone wants a quiet hour back at the stay. You think…", choices:["That sounds nice; I might join them","Great, we can split up and meet later","I’d rather find something we can all do"] },
  { dimension:"Nightlife", icon:"🌙", prompt:"After a long dinner, what sounds like the right kind of evening?", choices:["A slow walk, then a cozy wind-down","One more stop if the group’s feeling it","Let’s see where the night takes us"] },
  { dimension:"Nightlife", icon:"✨", prompt:"On vacation, your favorite late-night memory is usually…", choices:["A peaceful end to a day well spent","Laughing over one last drink or dessert","A spontaneous night that became a story"] },
];
const dimensions = ["Budget","Daily pace","Planning","Food","Social energy","Nightlife"];
const types = [
  { name:"The Slow Starter", line:"Good coffee. A little room. Then let’s go.", className:"day", art:"palm", share:"A soft start makes the whole day feel like yours." },
  { name:"The Daylight Drifter", line:"A little plan, a lot of room to wander.", className:"day", art:"sun", share:"One lovely anchor. Plenty of room around it." },
  { name:"The Easygoing Explorer", line:"A good plan is one that leaves room for more.", className:"day", art:"hill", share:"Curiosity first. The rest can find its way." },
  { name:"The After-Dinner Walker", line:"One more block. Maybe two.", className:"night", art:"moon", share:"The day can be full and the evening still unhurried." },
  { name:"The Sunset Seeker", line:"Let’s make a day of it, then see where we land.", className:"night", art:"sunset", share:"A full day, with a little magic left after dinner." },
  { name:"The Last-Light Wanderer", line:"The best plans leave space for a story.", className:"night", art:"stars", share:"Stay curious. The night has a little room left." },
];
const questionFlow = [
  { title:"Let’s make mornings feel good", prompt:"The group has a mix of early risers and slow starters. What kind of rhythm would you like to try?", options:["Keep a couple of mornings open","Pick one early outing, then leave the rest flexible","Agree on a relaxed meet-up time each day"] },
  { title:"A little clarity around spending", prompt:"People have different comfort zones. What would help everyone feel at ease before booking?", options:["Set a comfortable range for the shared stay","Share a couple of price options before deciding","Keep shared costs simple and plan splurges together"] },
  { title:"Together, with room to wander", prompt:"Some people recharge together; some like a little solo time. What sounds welcoming?", options:["Make it easy to split up and meet back later","Choose one shared anchor each day","Check in with each other as we go"] },
];

function defaultState(){ return { screen:"home", tripName:"", groupSize:5, answers:Array(12).fill(null), questionIndex:0, isSample:false, promptIndex:0, selectedPrompt:null, flowAnswers:[], completed:false }; }
function loadState(){ try { return {...defaultState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")}; } catch { return defaultState(); } }
let state = loadState();
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function esc(value){ return String(value).replace(/[&<>"']/g, ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch])); }
function showToast(message){ toast.textContent=message; toast.classList.add("show"); setTimeout(()=>toast.classList.remove("show"),2300); }
function setScreen(screen){ state.screen=screen; save(); render(); window.scrollTo({top:0,behavior:"smooth"}); }
function cardArt(kind){
  if(kind==="palm") return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><circle cx="27" cy="44" r="14" fill="none" stroke="currentColor" stroke-width="3"/><path d="M43 59c-4-24-2-38 6-52m-6 16C33 14 27 13 18 14m25 10c3-11 11-17 21-18M43 34c13-7 22-5 29 1m-31 9c-12-9-22-8-30-3m1 25c25-9 44-10 65-7" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`;
  if(kind==="moon"||kind==="stars") return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><path d="M47 9a19 19 0 1 0 20 25A21 21 0 0 1 47 9Z" fill="currentColor"/><path d="m9 61 20-25 15 17 12-21 17 29H9Z" fill="currentColor"/><path d="M15 69h52M21 73h38" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="m15 20 2 5 5 2-5 2-2 5-2-5-5-2 5-2 2-5Zm47 12 1.5 4 4 1.5-4 1.5-1.5 4-1.5-4-4-1.5 4-1.5 1.5-4Z" fill="currentColor"/></svg>`;
  return `<svg class="card-illustration" viewBox="0 0 80 76" aria-hidden="true"><circle cx="40" cy="37" r="19" fill="none" stroke="currentColor" stroke-width="3"/><path d="M40 3v9m0 50v10M6 37h9m50 0h9M16 13l7 7m34 34 7 7m0-48-7 7M23 54l-7 7" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M40 18v19l13 8" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`;
}

function rhythmArtwork(){return `<figure class="rhythm-figure"><svg class="rhythm-art" viewBox="0 0 680 360" role="img" aria-labelledby="rhythm-title rhythm-desc"><title id="rhythm-title">Different travel rhythms meet for lunch</title><desc id="rhythm-desc">Three equally weighted paths begin at different morning rhythms, meet at lunch, then continue toward the evening.</desc><text class="rhythm-label" x="24" y="77">slow start</text><text class="rhythm-label" x="24" y="181">early walk</text><text class="rhythm-label" x="24" y="297">coffee first</text><path class="rhythm-path path-coral" d="M24 102 C170 91 284 136 425 164 C502 179 579 210 652 231"/><path class="rhythm-path path-teal" d="M24 197 C166 196 288 187 425 164 C506 151 586 153 652 140"/><path class="rhythm-path path-blue" d="M24 278 C169 285 294 205 425 164 C509 139 585 111 652 91"/><path class="rhythm-connector" d="M425 130 L425 155"/><rect class="rhythm-anchor" x="337" y="82" width="176" height="48" rx="24"/><text class="rhythm-anchor-text" x="425" y="112" text-anchor="middle">meet for lunch</text><circle class="rhythm-node" cx="425" cy="164" r="7"/><text class="rhythm-time" x="24" y="340">morning</text><text class="rhythm-time" x="425" y="340" text-anchor="middle">midday</text><text class="rhythm-time" x="652" y="340" text-anchor="end">evening</text></svg><figcaption>One possible group rhythm · illustrative, not a prediction</figcaption></figure>`;}
function homeScreen(){ return `<section class="home-hero"><div class="hero-copy"><div class="eyebrow">A pre-trip check-in for good company</div><h1>Different ways to travel.<em>One good way to begin.</em><svg class="hero-underline" viewBox="0 0 500 14" aria-hidden="true"><path d="M2 8 C22 2 34 13 54 7 S84 3 103 8 134 12 152 7 182 2 202 8 231 12 251 7 282 3 301 8 333 12 353 7 384 3 403 8 434 12 453 7 479 4 498 8"/></svg></h1><p>Good Company helps friends talk about the trip they actually want—before bookings harden into expectations. Twelve small questions, gentle patterns, and a daily rhythm the whole group can live with.</p><div class="button-row"><button class="btn btn-coral" data-action="create">Start a trip <span>↗</span></button><button class="btn btn-secondary" data-action="sample">See a sample rhythm</button></div><div class="hero-proof">12 playful questions <i>·</i> Your answers stay yours <i>·</i> No wrong way to travel</div></div>${rhythmArtwork()}</section><section class="value-strip"><div class="value-item"><strong>01 · Take the Trip Check</strong>12 small questions. No right answers.</div><div class="value-item"><strong>02 · Meet your travel type</strong>A playful snapshot, just for this trip.</div><div class="value-item"><strong>03 · Find your group rhythm</strong>A few easy conversations, together.</div></section>`; }
function createScreen(){ return `<div class="create-header"><div class="eyebrow">Start with the trip, not the spreadsheet</div><h2>Who are we going with?</h2><p class="muted">Give your trip a name. You’ll get an invite to share with your people.</p></div><form class="panel form-panel" id="create-form"><label class="field-label" for="trip-name">What should we call it?</label><input class="text-input" id="trip-name" name="tripName" maxlength="48" placeholder="e.g. Palm Springs, finally" required value="${esc(state.tripName)}"><span class="field-label">How many of you are going?</span><div class="size-control"><button type="button" aria-label="Remove one traveler" data-action="size-down">−</button><span class="size-count"><span id="size-value">${state.groupSize}</span> people</span><button type="button" aria-label="Add one traveler" data-action="size-up">+</button></div><div class="privacy-note"><strong>Your answers stay yours.</strong> Friends see group patterns and conversation prompts, not your individual picks.</div><div class="button-row"><button class="btn btn-coral" type="submit">Create the trip <span>↗</span></button><button class="text-button" type="button" data-action="home">Back</button></div></form>`; }
function inviteScreen(){ const inviteUrl=`${location.href.split("#")[0]}#trip-${encodeURIComponent(state.tripName||"good-company")}`; return `<section class="center-page"><div class="eyebrow">Your trip is ready</div><h2>${esc(state.tripName || "A little getaway")}</h2><p class="muted">Send this little check-in to your people. Everyone gets a travel type; the group conversation opens after three people respond.</p><div class="invite-card"><div class="eyebrow" style="color:#fda28f">Your invitation</div><h3 class="serif" style="font-size:26px;margin:10px 0">“Before we book anything, let’s see what kind of trip we each want.”</h3><p>A small check-in for our trip. Find your travel type and help us find our group rhythm.</p><div class="link-row"><div class="link-box" id="invite-link">${esc(inviteUrl)}</div><button class="btn btn-coral" data-action="copy-invite">Copy link</button></div></div><div class="steps-list"><div class="step-row"><span class="step-num">1</span><span>Share the link in your group chat.</span></div><div class="step-row"><span class="step-num">2</span><span>Everyone answers 12 quick questions—no account needed.</span></div><div class="step-row"><span class="step-num">3</span><span>Come back together for patterns and a few easy conversations.</span></div></div><div class="privacy-note"><strong>Prototype note:</strong> this demo stores progress on this device only. Invite links won’t sync answers between different people yet.</div><div class="button-row"><button class="btn" data-action="begin">Take the Trip Check <span>→</span></button><button class="btn btn-secondary" data-action="home">Home</button></div></section>`; }
function quizScreen(){ const i=state.questionIndex,q=questions[i],chosen=state.answers[i]; return `<section class="quiz-wrap"><div class="quiz-top"><span>YOUR TRIP CHECK</span><span>${i+1} of ${questions.length}</span></div><div class="progress" aria-label="${i+1} of 12 questions complete"><span style="width:${((i+1)/questions.length)*100}%"></span></div><div class="panel question-panel"><div class="question-subtitle">A little about ${q.dimension.toLowerCase()}</div><h2 class="question-title">${q.prompt}</h2><p class="question-helper">Go with what feels right for this trip. There’s no wrong answer.</p><div class="answer-list">${q.choices.map((c,n)=>`<button class="answer-option ${chosen===n?"selected":""}" data-action="answer" data-value="${n}" aria-pressed="${chosen===n}"><span class="answer-icon">${q.icon}</span><span class="answer-copy">${c}</span><span class="answer-check">✓</span></button>`).join("")}</div><div class="quiz-actions"><button class="text-button" data-action="quiz-back">${i===0?"Save for later":"← Back"}</button><button class="btn btn-coral" data-action="quiz-next" ${chosen===null?"disabled":""}>${i===questions.length-1?"Meet your type":"Next"} <span>→</span></button></div></div><p class="tiny-note" style="text-align:center;margin-top:13px">Your picks are private. We only use them to make your personal result.</p></section>`; }
function score(){ const out=Object.fromEntries(dimensions.map(d=>[d,[]])); questions.forEach((q,i)=>{if(state.answers[i]!==null) out[q.dimension].push(state.answers[i]??1);}); return Object.fromEntries(dimensions.map(d=>{const a=out[d]; const mean=a.length?a.reduce((x,y)=>x+y,0)/a.length:2; return [d,Math.round((mean-1)*50)];})); }
function travelType(scores){ const energy=(scores["Daily pace"]+scores[PlanningKey()]+scores.Food+scores["Nightlife"])/4; const social=(scores["Social energy"]+scores["Nightlife"])/2; const dayLean=scores["Daily pace"]<50 && scores.Nightlife<55; let index=dayLean?(energy<30?0:energy<58?1:2):(social<34?3:social<67?4:5); return types[index]; }
function PlanningKey(){return "Planning";}
function profileMarkup(scores){return `<div class="profile-list">${dimensions.map((d,i)=>`<div class="dimension-row"><span class="dimension-label">${d}</span><span class="dimension-track"><span class="dimension-fill" style="width:${Math.max(7,scores[d])}%;background:${i%2?"var(--teal)":"var(--blue)"}"></span></span><span class="dimension-value">${scores[d]<34?"More room":"Somewhere between"}</span></div>`).join("")}</div>`;}
function resultScreen(){ const scores=score(),type=travelType(scores); return `<section class="center-page"><div class="eyebrow">Your travel type · just for this trip</div><h2>A little more you, in the mix.</h2><p class="muted">This is a playful snapshot of what you picked—not a personality test, and not a label that has to stick.</p><div class="card-layout"><article class="type-card ${type.className}" id="share-card"><div class="card-topline"><span>Your travel type</span><span>${type.className==="day"?"Day card":"Night card"}</span></div><div class="card-middle">${cardArt(type.art)}<div class="card-overline">An affectionate little snapshot</div><h3 class="card-title">${type.name}</h3><div class="card-tagline">${type.line}</div></div><div class="card-bottomline"><span>good company.</span><span>Take the Trip Check ↗</span></div></article><div class="result-copy"><span class="eyebrow">A private look at your answers</span>${profileMarkup(scores)}<p class="tiny-note">Your group won’t see these individual picks or dimension details. They’ll see patterns once enough people answer.</p><div class="share-actions"><button class="btn btn-coral" data-action="share-card" data-format="story">Preview Story card ↗</button><button class="btn btn-secondary" data-action="share-card" data-format="square">Preview square card ↗</button><button class="text-button" data-action="copy-type">Copy my result</button></div><p class="tiny-note" style="margin-top:13px">${esc(type.share)}</p></div></div><div style="display:flex;justify-content:space-between;gap:15px;align-items:center;margin-top:28px"><button class="text-button" data-action="delete-answer">Delete my answers</button><button class="btn" data-action="group">See our group rhythm <span>→</span></button></div></section>`; }
function insightPanel(){ return `<div class="panel"><div class="eyebrow">Based on 4 of 5 responses</div><h3 class="serif" style="font-size:25px;margin-top:7px">A few things to keep in mind</h3><div class="insight-list"><div class="insight-item"><div class="insight-symbol">☀️</div><div><strong>Everyone has room for an unhurried start</strong><span>A slow first morning might help the trip feel good from day one.</span></div></div><div class="insight-item"><div class="insight-symbol">🍽️</div><div><strong>A shared meal could be a lovely anchor</strong><span>Food matters to a few of you. Picking one dinner together could be a fun place to start.</span></div></div><div class="insight-item"><div class="insight-symbol">🌿</div><div><strong>Some of you like a little breathing room</strong><span>It could feel easy to leave space for people to wander, then meet back up.</span></div></div></div><p class="tiny-note" style="margin:13px 0 0">Patterns, not people. No individual answers or scores appear here.</p></div>`; }
function conversationCard(){ const i=state.promptIndex, q=questionFlow[i]; if(state.promptIndex>=questionFlow.length) return `<div class="conversation-card"><div class="conversation-step">A good start, together</div><div style="font-size:31px;margin-bottom:9px">✳</div><h3>You’ve made a little room for everyone.</h3><p>Your group has a few starting points to bring into the planning chat. Nothing is set in stone—you can come back to these whenever it helps.</p><div class="result-banner">“${esc(state.flowAnswers[0] || "Let’s keep a couple of mornings open and decide together.") }”</div><div class="conversation-footer"><button class="text-button" data-action="flow-restart">Start another</button><button class="btn" data-action="home">All done ✓</button></div></div>`; return `<div class="conversation-card"><div class="conversation-step">A quick group flow · ${i+1} of ${questionFlow.length}</div><h3>${q.title}</h3><p>${q.prompt}</p><div class="prompt-options">${q.options.map((o,n)=>`<button class="prompt-option ${state.selectedPrompt===o?"selected":""}" data-action="prompt-choice" data-value="${n}">${o}</button>`).join("")}</div><div class="conversation-footer"><button class="text-button" data-action="prompt-skip">Maybe later</button><button class="btn" data-action="prompt-next" ${state.selectedPrompt?"":"disabled"}>${i===questionFlow.length-1?"Keep this thought":"Next"} →</button></div></div>`; }
function dashboardScreen(){ return `<section><div class="section-head"><div><div class="eyebrow">The ${esc(state.tripName||"weekend")}, together</div><h2>Different days. One good group.</h2></div><button class="btn btn-secondary" data-action="copy-invite">Invite your people ↗</button></div><div class="dashboard-grid"><div>${insightPanel()}<div class="panel response-card" style="margin-top:15px"><div><div class="eyebrow">Your group, so far</div><div class="response-count">4<small> / 5 answered</small></div><p class="tiny-note" style="margin:7px 0 0">The shared view opens after three people check in.</p></div><div class="avatar-stack" aria-label="Four friends have answered"><span class="avatar">A</span><span class="avatar">M</span><span class="avatar">J</span><span class="avatar">Y</span><span class="avatar">+</span></div></div></div><div>${conversationCard()}<div class="privacy-note"><strong>A note on this prototype:</strong> sample group patterns are illustrative. In a live product, people’s individual answers would remain private.</div></div></div></section>`; }
function completionScreen(){return `<section class="completion-screen"><div class="completion-icon">✓</div><div class="eyebrow">That’s everyone in the room</div><h2>You're part of the group rhythm.</h2><p class="muted">Your choice is just one voice in the mix. The best next step is whatever feels easy for your group.</p><div class="result-banner" style="text-align:left;margin:25px 0">Your private response has been saved on this device. You can revisit your travel type or delete your answers anytime.</div><div class="button-row" style="justify-content:center"><button class="btn" data-action="result">See my travel type</button><button class="btn btn-secondary" data-action="group">Back to the group</button></div></section>`;}
function render(){ let view={home:homeScreen,create:createScreen,invite:inviteScreen,quiz:quizScreen,result:resultScreen,group:dashboardScreen,complete:completionScreen}[state.screen]||homeScreen; app.innerHTML=view(); document.querySelectorAll(".btn:disabled").forEach(b=>{b.style.opacity=".45";b.style.cursor="not-allowed";}); }
async function copyText(text){ try{await navigator.clipboard.writeText(text);showToast("Copied. Ready to share!");}catch{showToast("Copy isn’t available here—select the link to copy it.");} }
function drawShareCard(format="story") {
  const square=format==="square",type=travelType(score()),night=type.className==="night";
  const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=square?1080:1920;
  const c=canvas.getContext("2d"),ink="#021A25",paper="#FBF7EF",coral="#FE664D",teal="#67ADAC";
  const bg=night?teal:coral,w=canvas.width,h=canvas.height,center=w/2;
  c.fillStyle=bg;c.fillRect(0,0,w,h);c.fillStyle="rgba(255,255,255,.11)";c.beginPath();c.arc(w*.84,h*.19,w*.28,0,Math.PI*2);c.fill();
  c.strokeStyle="rgba(2,26,37,.55)";c.lineWidth=5;c.lineCap="round";c.beginPath();
  if(square){c.moveTo(38,790);c.bezierCurveTo(260,920,770,870,1042,680);}else{c.moveTo(25,1360);c.bezierCurveTo(320,1540,760,1510,1050,1280);}c.stroke();
  c.fillStyle=ink;c.textAlign="left";c.font="700 28px Arial, sans-serif";c.letterSpacing="5px";c.fillText("YOUR TRAVEL TYPE",88,square?115:245);
  c.textAlign="right";c.fillText(night?"NIGHT CARD":"DAY CARD",992,square?115:245);
  c.textAlign="center";c.letterSpacing="0px";
  drawShareIllustration(c,type.art,center,square?280:600,1.7);
  c.font="500 30px Georgia, serif";c.fillText("An affectionate little snapshot",center,square?466:900);
  c.font=`italic 600 ${square?75:104}px Georgia, serif`;
  wrapShareText(c,type.name,center,square?560:1030,900,square?82:112);
  c.font="500 32px Arial, sans-serif";
  wrapShareText(c,type.line,center,square?744:1320,860,46);
  const footerY=square?946:1634;
  c.strokeStyle="rgba(2,26,37,.42)";c.lineWidth=2;c.beginPath();c.moveTo(88,footerY-55);c.lineTo(992,footerY-55);c.stroke();
  c.textAlign="left";c.font="700 24px Arial, sans-serif";c.fillText("good company.",88,footerY);
  c.textAlign="right";c.font="600 22px Arial, sans-serif";c.fillText("Take the Trip Check ↗",992,footerY);
  c.textAlign="left";
  return {canvas,type};
}
function drawShareIllustration(c,kind,cx,cy,scale){
  c.save();c.translate(cx,cy);c.scale(scale,scale);c.strokeStyle="#021A25";c.fillStyle="#021A25";c.lineWidth=3;c.lineCap="round";c.lineJoin="round";
  if(kind==="palm"||kind==="sun"||kind==="sunset"){
    c.beginPath();c.arc(-19,4,14,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(8,29);c.quadraticCurveTo(4,-8,20,-35);c.moveTo(13,-16);c.quadraticCurveTo(-3,-32,-20,-28);c.moveTo(13,-16);c.quadraticCurveTo(27,-38,43,-33);c.moveTo(14,-5);c.quadraticCurveTo(36,-18,51,-5);c.moveTo(12,-8);c.quadraticCurveTo(-9,-15,-25,-1);c.moveTo(-34,31);c.quadraticCurveTo(5,17,47,28);c.stroke();
  } else {
    c.beginPath();c.arc(19,-23,17,-.9,2.4);c.arc(28,-28,17,2.25,5.2,true);c.fill();
    c.beginPath();c.moveTo(-49,32);c.lineTo(-18,-8);c.lineTo(0,14);c.lineTo(23,-18);c.lineTo(53,32);c.closePath();c.fill();
    c.beginPath();c.moveTo(-43,40);c.lineTo(43,40);c.moveTo(-33,47);c.lineTo(33,47);c.stroke();
    c.beginPath();c.moveTo(-45,-39);c.lineTo(-42,-31);c.lineTo(-34,-28);c.lineTo(-42,-25);c.lineTo(-45,-17);c.lineTo(-48,-25);c.lineTo(-56,-28);c.lineTo(-48,-31);c.closePath();c.fill();
  }
  c.restore();
}
function wrapShareText(c,text,center,y,maxWidth,lineHeight){
  const words=text.split(" ");let line="",lines=[];
  for(const word of words){const candidate=line?`${line} ${word}`:word;if(c.measureText(candidate).width>maxWidth&&line){lines.push(line);line=word;}else line=candidate;}
  if(line)lines.push(line);const start=y-((lines.length-1)*lineHeight)/2;lines.forEach((item,index)=>c.fillText(item,center,start+index*lineHeight));
}
function sharePreviewMarkup(format,imageUrl){
  const type=travelType(score()),hasPublicUrl=Boolean(publicTripCheckUrl());
  return `<div class="share-modal-backdrop" data-action="close-share-backdrop"><section class="share-modal" role="dialog" aria-modal="true" aria-labelledby="share-title"><button class="share-close" data-action="close-share" aria-label="Close preview">×</button><div class="eyebrow">Your card, your call</div><h2 id="share-title">Take a look before it leaves your phone.</h2><p class="muted">This card shows your travel type only. Your trip name, answers, dimension details, budget, and group patterns stay private.</p><div class="share-tabs" role="group" aria-label="Choose card format"><button class="share-tab ${format==="story"?"active":""}" data-action="share-format" data-format="story" aria-pressed="${format==="story"}">Story · 9:16</button><button class="share-tab ${format==="square"?"active":""}" data-action="share-format" data-format="square" aria-pressed="${format==="square"}">Square · 1:1</button></div><div class="share-image-frame ${format}" aria-label="Preview of ${format} card for ${esc(type.name)}"><img src="${imageUrl}" alt="${esc(type.name)} travel type card in the ${type.className==="day"?"coral day":"teal night"} suit" /></div><div class="share-modal-actions"><button class="btn btn-coral" data-action="save-share-card">Save image</button><button class="btn btn-secondary" data-action="native-share-card">Share…</button><button class="text-button" data-action="copy-share-link" ${hasPublicUrl?"":"disabled"}>${hasPublicUrl?"Copy Trip Check link":"Public link available when published"}</button></div><p class="tiny-note share-safe-note">${format==="story"?"Story layout keeps key text within a generous center safe area. ":"Square card is 1:1. "}No auto-posting. You choose what to save or share.${hasPublicUrl?"":" This local preview does not have a public Trip Check URL yet."}</p></section></div>`;
}
async function openSharePreview(format="story"){
  shareFormat=format;await document.fonts.ready;const {canvas}=drawShareCard(format);
  document.querySelector(".share-modal-backdrop")?.remove();
  document.body.insertAdjacentHTML("beforeend",sharePreviewMarkup(format,canvas.toDataURL("image/png")));
  document.querySelector(".share-close")?.focus();
}
function closeSharePreview(){document.querySelector(".share-modal-backdrop")?.remove();}
async function saveShareCard(){const {canvas}=drawShareCard(shareFormat);const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`good-company-travel-type-${shareFormat}.png`;a.click();showToast("Your card is saved. Share it wherever you like.");}
async function nativeShareCard(){
  const {canvas,type}=drawShareCard(shareFormat);
  if(!navigator.share||!canvas.toBlob){showToast("Sharing isn’t available here. You can save the image or copy the link.");return;}
  canvas.toBlob(async blob=>{
    if(!blob)return showToast("This browser couldn’t prepare the image. Try saving it instead.");
    const file=new File([blob],`good-company-travel-type-${shareFormat}.png`,{type:"image/png"});
    try{
      if(!navigator.canShare?.({files:[file]})){showToast("Image sharing isn’t available here. Save the card or copy the link.");return;}
      const url=publicTripCheckUrl(),text=url?`I’m ${type.name}. Take the Trip Check: ${url}`:`I’m ${type.name}. Take the Trip Check with Good Company.`;
      await navigator.share({files:[file],title:"My Good Company travel type",text});
    }catch(error){if(error.name!=="AbortError")showToast("Sharing didn’t open. You can save the image instead.");}
  },"image/png");
}
function publicTripCheckUrl(){
  if(!["http:","https:"].includes(location.protocol)||["localhost","127.0.0.1","::1","github.com","raw.githubusercontent.com"].includes(location.hostname))return null;
  return location.href.split("#")[0];
}
function copyPublicTripCheckLink(){const url=publicTripCheckUrl();if(url)copyText(url);else showToast("A public Trip Check link will be ready when the app is published.");}

app.addEventListener("submit",event=>{if(event.target.id==="create-form"){event.preventDefault();state.tripName=new FormData(event.target).get("tripName").trim();state.answers=Array(12).fill(null);state.questionIndex=0;state.isSample=false;setScreen("invite");}});
document.addEventListener("click",event=>{const el=event.target.closest("[data-action]");if(!el)return;const action=el.dataset.action;switch(action){case"home":state.screen="home";state.isSample=false;save();render();break;case"create":state.groupSize=5;setScreen("create");break;case"sample":state.tripName="A long weekend in Ojai";state.isSample=true;state.screen="group";state.promptIndex=0;state.selectedPrompt=null;state.flowAnswers=[];save();render();break;case"size-down":state.groupSize=Math.max(3,state.groupSize-1);save();render();break;case"size-up":state.groupSize=Math.min(10,state.groupSize+1);save();render();break;case"copy-invite":copyText(document.querySelector("#invite-link")?.textContent||`${location.href.split("#")[0]}#trip-${encodeURIComponent(state.tripName||"good-company")}`);break;case"begin":state.questionIndex=0;setScreen("quiz");break;case"answer":state.answers[state.questionIndex]=Number(el.dataset.value);save();render();break;case"quiz-next":if(state.answers[state.questionIndex]===null)return;if(state.questionIndex<11){state.questionIndex++;save();render();}else{state.completed=true;setScreen("result");}break;case"quiz-back":if(state.questionIndex>0){state.questionIndex--;save();render();}else setScreen("invite");break;case"result":setScreen("result");break;case"group":state.screen="group";save();render();break;case"share-card":openSharePreview(el.dataset.format);break;case"share-format":openSharePreview(el.dataset.format);break;case"close-share":closeSharePreview();break;case"close-share-backdrop":if(event.target===el)closeSharePreview();break;case"save-share-card":saveShareCard();break;case"native-share-card":nativeShareCard();break;case"copy-share-link":copyPublicTripCheckLink();break;case"copy-type":{const url=publicTripCheckUrl();copyText(`${travelType(score()).name} — ${travelType(score()).line}${url?` Take the Trip Check: ${url}`:""}`);break;}case"delete-answer":if(confirm("Delete your answers from this device? This cannot be undone.")){state.answers=Array(12).fill(null);state.completed=false;state.screen="home";save();render();showToast("Your answers have been deleted.");}break;case"prompt-choice":state.selectedPrompt=questionFlow[state.promptIndex].options[Number(el.dataset.value)];save();render();break;case"prompt-next":if(!state.selectedPrompt)return;state.flowAnswers[state.promptIndex]=state.selectedPrompt;state.promptIndex++;state.selectedPrompt=null;if(state.promptIndex>=questionFlow.length){state.screen="complete";}save();render();break;case"prompt-skip":state.flowAnswers[state.promptIndex]=null;state.promptIndex++;state.selectedPrompt=null;if(state.promptIndex>=questionFlow.length)state.screen="complete";save();render();break;case"flow-restart":state.promptIndex=0;state.selectedPrompt=null;state.flowAnswers=[];save();render();break;}});
document.addEventListener("keydown",event=>{if(event.key==="Escape")closeSharePreview();});
render();
